In [32]:
import pandas as pd
import numpy as np

In [2]:
s = pd.Series([10, 20, 30, 40])

print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [3]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [21, 22, 23],
    "City": ["Delhi", "Mumbai", "Hyderabad"]
}

df = pd.DataFrame(data)

print(df)

      Name  Age       City
0    Alice   21      Delhi
1      Bob   22     Mumbai
2  Charlie   23  Hyderabad

In [4]:
print(df.head())

      Name  Age       City
0    Alice   21      Delhi
1      Bob   22     Mumbai
2  Charlie   23  Hyderabad

In [6]:
print(df.head(1))

    Name  Age   City
0  Alice   21  Delhi

In [7]:
print(df.info())

print(df.shape)

print(df.columns)

print(df.dtypes)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None
(3, 3)
Index(['Name', 'Age', 'City'], dtype='object')
Name    object
Age      int64
City    object
dtype: object

In [8]:
print(df.describe())

        Age
count   3.0
mean   22.0
std     1.0
min    21.0
25%    21.5
50%    22.0
75%    22.5
max    23.0

In [9]:
print(df[1:2])

  Name  Age    City
1  Bob   22  Mumbai

In [13]:
print(df["Name"])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [14]:
print(df.loc[0])

print(df.loc[0:2])

print(df.iloc[0])

print(df.iloc[0:2])

Name    Alice
Age        21
City    Delhi
Name: 0, dtype: object
      Name  Age       City
0    Alice   21      Delhi
1      Bob   22     Mumbai
2  Charlie   23  Hyderabad
Name    Alice
Age        21
City    Delhi
Name: 0, dtype: object
    Name  Age    City
0  Alice   21   Delhi
1    Bob   22  Mumbai

In [15]:
print(df.loc[0])

print(df.loc[0:2])

print(df.iloc[0])

print(df.iloc[0:2])

Name    Alice
Age        21
City    Delhi
Name: 0, dtype: object
      Name  Age       City
0    Alice   21      Delhi
1      Bob   22     Mumbai
2  Charlie   23  Hyderabad
Name    Alice
Age        21
City    Delhi
Name: 0, dtype: object
    Name  Age    City
0  Alice   21   Delhi
1    Bob   22  Mumbai

In [16]:
df["Salary"] = [30000, 40000, 50000]

print(df)

      Name  Age       City  Salary
0    Alice   21      Delhi   30000
1      Bob   22     Mumbai   40000
2  Charlie   23  Hyderabad   50000

In [17]:
df["Age"] = df["Age"] + 1

In [18]:
df.isnull()

df.isnull().sum()

Name      0
Age       0
City      0
Salary    0
dtype: int64

In [19]:
df.sort_values("Age")

df.sort_values("Age", ascending=False)

      Name  Age       City  Salary
2  Charlie   24  Hyderabad   50000
1      Bob   23     Mumbai   40000
0    Alice   22      Delhi   30000

In [20]:
df

      Name  Age       City  Salary
0    Alice   22      Delhi   30000
1      Bob   23     Mumbai   40000
2  Charlie   24  Hyderabad   50000

In [21]:
df["department"] = ["IT","IT","HR"]
df

      Name  Age       City  Salary department
0    Alice   22      Delhi   30000         IT
1      Bob   23     Mumbai   40000         IT
2  Charlie   24  Hyderabad   50000         HR

In [28]:
print(df.groupby("department")["Salary"].sum())
df

department
HR    50000
IT    70000
Name: Salary, dtype: int64

      Name  Age       City  Salary department
0    Alice   22      Delhi   30000         IT
1      Bob   23     Mumbai   40000         IT
2  Charlie   24  Hyderabad   50000         HR

In [33]:
df["Home Town"] = ["Guntur","Vijayawada",np.nan]
df

      Name  Age       City  Salary department   Home Town
0    Alice   22      Delhi   30000         IT      Guntur
1      Bob   23     Mumbai   40000         IT  Vijayawada
2  Charlie   24  Hyderabad   50000         HR         NaN

In [35]:
df.fillna("Ongole",inplace=True)
df

      Name  Age       City  Salary department   Home Town
0    Alice   22      Delhi   30000         IT      Guntur
1      Bob   23     Mumbai   40000         IT  Vijayawada
2  Charlie   24  Hyderabad   50000         HR      Ongole

In [36]:
students = pd.DataFrame({
    "ID" : [1,2,3],
    "Name" : ["Alice","Bob","Charlie"]
})

In [37]:
marks = pd.DataFrame({
    "ID": [1, 2, 4],
    "Marks": [85, 90, 75]
})

In [38]:
result = pd.merge(students, marks, on="ID", how="left")
print(result)

   ID     Name  Marks
0   1    Alice   85.0
1   2      Bob   90.0
2   3  Charlie    NaN

In [39]:
result = pd.merge(students, marks, on="ID", how="inner")
print(result)

   ID   Name  Marks
0   1  Alice     85
1   2    Bob     90

In [41]:
result = pd.merge(students, marks, on="ID", how="right")
print(result)

   ID   Name  Marks
0   1  Alice     85
1   2    Bob     90
2   4    NaN     75

In [54]:
df = pd.DataFrame({
    "Date": ["2026-08-01", "2026-08-02", "2026-08-05"]
})

In [56]:
df["Date"] = pd.to_datetime(df["Date"])

In [57]:
df["Year"] = df["Date"].dt.year

In [58]:
df["Day"] = df["Date"].dt.day

In [59]:
df["Weekday"] = df["Date"].dt.day_name()

In [60]:
df

        Date  Year  Day    Weekday
0 2026-08-01  2026    1   Saturday
1 2026-08-02  2026    2     Sunday
2 2026-08-05  2026    5  Wednesday